qbic-pipelines/rnadeseq

bin/DESeq.v2.7.R
main.nf
nextflow.config

- added log2FC threshold option
- tables folder to count_tables and DE_genes_tables
- removed log2fold unnecessary table
- corrected barplots gene counts
- removed heatmap for highest variance genes
Solves issues #9 #8 #6

Several bugfixes and features

---

README.md
bin/gProfileR.R
environment.yml

- added gprofiler
- added dependencies for gprofiler in container

Pathway analysis

---

assets/RNAseq_report.Rmd

Some adjustments for grammar/typos

---

README.md

update minimal NXF badge

---

CHANGELOG.md
bin/DESeq2.R

- Boxplot counts are now vst transformed
- Possible to plot boxplots for requested genes that are not DE
- More comprehensive variable names and comments in DESeq script

Boxplot counts fix

---

bin/DESeq2.R

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

Polish print statements

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
environment.yml
nextflow.config

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

Bugfix boxplots requested genes

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
bin/DESeq2.R
environment.yml
nextflow.config

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

Release1.3.1

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
assets/RNAseq_report.Rmd
bin/DESeq2.R
bin/Execute_report.R
bin/pathway_analysis.R
environment.yml
main.nf
nextflow.config

Release 1.3.2

---

CHANGELOG.md
assets/RNAseq_report.Rmd
bin/DESeq2.R
modules/local/pathway_analysis.nf
nextflow_schema.json

This fixes issue #88 and introduces enhanced volcano plots which mark significant genes.

Enhanced volcano plots

---

CHANGELOG.md
testdata/Sample_preparations.tsv
testdata/design_batcheffect.txt

This only added/modified test files for the batcheffect test, no code was changed
//TODO: Change nf-core? In "If necessary, also...", this does not make much sense, maybe just delete?

Added second design for batch effect, modified sampleprep

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
environment.yml
nextflow.config

//TODO: Change nf-core? In "If necessary, also...", this does not make much sense, maybe just delete?

Version 2.0.1 bump

---

.github/workflows/ci.yml
CHANGELOG.md
nextflow.config

//TODO: Change nf-core? In "If necessary, also...", this does not make much sense, maybe just delete?

Fixed some versions for the release 2.0.1

---

CHANGELOG.md
assets/RNAseq_report.Rmd

This PR enables batch correction for rsem/salmon input which previously did not work and improves the error messages if some rsem/salmon files are not found. Closes #155

Fixed batch correction for star input (2.5)

---

CHANGELOG.md
assets/RNAseq_report.Rmd
tests/test_batcheffect.yml

Mini PR for checking if 5sum for test_batcheffect ist stable (5)

---

CHANGELOG.md
nextflow.config

Prepare release 2.1

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
environment.yml
modules/local/report.nf

More version bumps

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/ci.yml
.nf-core.yml
CHANGELOG.md
nextflow.config
nextflow_schema.json
tests/test_star_rsem.yml

Fixed ci.yml test, updated schema

---

CHANGELOG.md
testdata/software_versions_rsem.yml
testdata/software_versions_salmon.yml

This adds the yml files, merge first before merging the code changes

Added yml files for rsem/salmon software versions

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
environment.yml
modules/local/report.nf

Rebump versions before release

Version re-bump

---

.github/workflows/ci.yml
Dockerfile
environment.yml
modules/local/report.nf

Bumped again all versions

---

assets/RNAseq_report.Rmd
bin/Execute_report.R
conf/test.config
conf/test_full.config
modules/local/report.nf
nextflow.config
nextflow_schema.json

This PR reintroduces an optional --quote parameter

2) Add optional --quote param

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
assets/RNAseq_report.Rmd
docs/output.md
environment.yml
modules/local/report.nf
tests/test_star_rsem.yml
tests/test_star_salmon.yml

This PR removes rsem/salmon files from the results.zip and instead adds a metadata doc listing their file names for reproducibility

4) No alignfiles

---

CHANGELOG.md
assets/RNAseq_report.Rmd

The layout of the gostplots was previously not working, the interactive moving did not function. This PR fixes that problem. It also adds a computational methods section to the report even if no software_versions were provided

Gostplot fix, comp methods change

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
environment.yml
modules/local/report.nf
nextflow.config

Software version bumps for release 2.2

---

.github/ISSUE_TEMPLATE/config.yml
CHANGELOG.md
assets/RNAseq_report.Rmd
nextflow_schema.json

This PR just adds some minor changes from the suggestions of the PR 219 review

Add suggestions for release 2.2

---

CHANGELOG.md
assets/RNAseq_report.Rmd
conf/test_custom_gmt.config
docs/usage.md

Also fix some things from TE's comments in #233

Add distance info for heatmaps, add heatmap tables, change volcano jitter to points

---

.github/workflows/branch.yml
CHANGELOG.md

second attempt at fixing branch protection

---

.github/workflows/branch.yml
CHANGELOG.md

third attempt at fixing branch protection

---

.nf-core.yml
modules/local/report.nf
nextflow.config
nextflow_schema.json
workflows/rnadeseq.nf

Fix path issue with report file

---

.nf-core.yml
CHANGELOG.md
assets/RNAseq_report.Rmd
bin/Execute_report.R
modules/local/report.nf
nextflow.config
nextflow_schema.json
workflows/rnadeseq.nf

Fix report issue with missing logo

---

CHANGELOG.md
assets/RNAseq_report.Rmd

Changed the report text that shows when the gprofiler GMT file could not be downloaded, removed hard-coded comment about usage of gprofiler databases KEGG and REAC in the report

2 - Changed/removed some report texts

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
docs/usage.md
environment.yml
modules/local/report.nf
nextflow.config

4 - Bumped versions to 2.4 for next release

---

CHANGELOG.md
docs/usage.md

Add missing params to usage docs

---

.github/workflows/ci.yml
.gitignore
CHANGELOG.md
Dockerfile
assets/RNAseq_report.Rmd
docs/output.md
docs/usage.md
environment.yml
modules/local/report.nf
nextflow.config
tests/test.yml
tests/test_batcheffect.yml
tests/test_contrast_list.yml
tests/test_contrast_matrix.yml
tests/test_custom_gmt.yml
tests/test_full.yml
tests/test_no_multiqc.yml
tests/test_relevel.yml
tests/test_smrnaseq.yml
tests/test_star_rsem.yml
tests/test_star_salmon.yml
tests/test_use_vst.yml

Add EnhancedVolcano

---

CHANGELOG.md
assets/RNAseq_report.Rmd

Hotfix colors volcano plot

---

CHANGELOG.md
assets/RNAseq_report.Rmd

Put gprofiler in tabs

---

CHANGELOG.md
assets/rnadeseq_report.Rmd
docs/usage.md
testdata/contrast_matrix.tsv
tests/test_contrast_matrix.yml

Fixes contrast conditions in Summary which were not displayed correctly.

Bugfix summary 
