CHANGELOG.md
assets/RNAseq_report.Rmd
bin/DESeq2.R
bin/Execute_report.R
conf/test_use_vst.config
modules/local/deseq2.nf
modules/local/pathway_analysis.nf
modules/local/report.nf
nextflow.config
nextflow_schema.json

This PR is in regard to issue #99 as a follow-up. It changes the DE analysis and report to use a vst normalization if rlog is skipped; otherwise, the rlog normalization is used.

Made normalization switchable (vst/rlog)

---

.github/workflows/ci.yml
.github/workflows/linting_comment.yml
CHANGELOG.md
bin/DESeq2.R
docs/usage.md

This PR fixes a relevel bug and adds test_relevel to the github checks. It also updates the doc to state that the --species param is unnecessary if skipping pathway analysis.

Updated doc, fixed relevel bug, added relevel to github tests

---

CHANGELOG.md
assets/RNAseq_report.Rmd
tests/test_batcheffect.yml

This PR closes #89, boxplots are now only generated for those contrasts listed in contrast_list/matrix if these files are provided

Consider contrast files for boxplots (8)

---

.github/workflows/ci.yml
CHANGELOG.md
Dockerfile
assets/RNAseq_report.Rmd
environment.yml
modules/local/report.nf

This fixes a formatting error in the report html, closes #194

1) Fix enriched pathways display error in report

---

assets/RNAseq_report.Rmd
tests/test_star_rsem.yml

This adds the gprofiler version string to the report

3) Add gprofiler version

---

CHANGELOG.md
conf/test_relevel.config

This PR changes the relevel github file path to the qbic-pipelines repo

Changed relevel github path to qbic-pipelines

---

CHANGELOG.md
assets/RNAseq_report.Rmd
lib/NfcoreTemplate.groovy
tests/test.yml
tests/test_batcheffect.yml
tests/test_contrast_list.yml
tests/test_contrast_matrix.yml
tests/test_custom_gmt.yml
tests/test_full.yml
tests/test_no_multiqc.yml
tests/test_relevel.yml
tests/test_star_rsem.yml
tests/test_star_salmon.yml
tests/test_use_vst.yml

This PR finally (!) makes relevel functional

fixed relevel bug

---

.github/workflows/push_github_container_reg.yml
.nf-core.yml
CHANGELOG.md
assets/RNAseq_report.Rmd
environment.yml

The kaleido package recently stopped working in the container; it was used for the save_image() function to export heatmaply plots. This PR exchanges those heatmaps for plots done with pheatmap so they can be saved without the function

Fixed heatmaps and removed kaleido from container

---

CHANGELOG.md
assets/RNAseq_report.Rmd

Fixes https://github.com/qbic-pipelines/rnadeseq/issues/216, missing gene_names are now replaced by gene_ids

Replace missing GTF gene_names with IDs

---

CHANGELOG.md
assets/RNAseq_report.Rmd

Add logic to better check which multiqc version is provided (sometimes both the old and the new table file are present in the mqc).

Fix new multiqc

---

.github/workflows/branch.yml
CHANGELOG.md

Fix branch protection bug

---

.github/workflows/branch.yml
.nf-core.yml
CHANGELOG.md
assets/RNAseq_report.Rmd
bin/Execute_report.R
modules/local/report.nf
nextflow.config
nextflow_schema.json
workflows/rnadeseq.nf

Second release PR after I found a bug in the previous one

Release 2.3 - This time for real

---

CHANGELOG.md
Dockerfile
environment.yml
modules/local/report.nf
nextflow.config

Changed pipeline version to dev

1 - Changed pipeline version to dev

---

CHANGELOG.md
assets/RNAseq_report.Rmd

Added background list to output for reproducibility, removed hard-coded gprofiler DBs from report.
Also slightly changed the report text that shows when the gprofiler GMT file could not be downloaded so that it integrates better into the surrounding text.
This PR directly raises the pipeline version to 2.4 instead of setting it to dev as I will release after this PR

3 - Write background list

---

.github/workflows/ci.yml
CHANGELOG.md

Updates actions/upload-artifact to v4 to fix a CI bug

Fixed bug with github actions

---

CHANGELOG.md
assets/RNAseq_report.Rmd
bin/Execute_report.R
conf/test.config
modules/local/report.nf
nextflow.config
nextflow_schema.json
tests/test.yml

... in order to allow different values for the qval in DE analysis and pathway analysis. If not set by the user, the pathway analysis will continue to use the same threshold as for DE analysis.

Added separate param for setting adjusted pval threshold for pathway analysis

---

CHANGELOG.md
assets/RNAseq_report.Rmd
tests/test_star_rsem.yml
tests/test_star_salmon.yml

Get raw gene count tables from either Salmon and RSEM analysis 

---

CHANGELOG.md
assets/RNAseq_report.Rmd
docs/usage.md

For pathway analyses where many pathways are enriched, the ggsave function throws an error when trying to save the enrichment plots. This PR adds trycatches to allow the pipeline to continue; the plots are in such a case not saved

Add trycatch to enrichment plots

---

assets/RNAseq_report.Rmd
bin/Execute_report.R

Fixes remarks from #257 by removing excessive check of the pathway_adj_pval_threshold param, adding a default description and prettifying

Fix remarks from #257 for release 2.5

---

CHANGELOG.md
assets/RNAseq_report.Rmd
docs/output.md

Apply color scheme of EnhancedVolcano to plotly volcano

---

CHANGELOG.md
assets/RNAseq_report.Rmd
docs/usage.md

Fixes the ggsave error when many genes are DE.
With many genes being DE, one might need to adapt resource requirements.
Therefore, usage docs were updated to better document what to do in case of 137 error (OOM-out of memory).
```
Quitting from lines 1936-2369 [load_PA_libs] (RNAseq_report.Rmd)
Error:
! One or both dimensions exceed the maximum (50000px).
- Use `options(ragg.max_dim = ...)` to change the max
Warning: May cause the R session to crash
Backtrace:
1. ggplot2::ggsave(...)
2. ggplot2 (local) dev(...)
3. ggplot2 (local) png_dev(..., res = dpi, units = "in")
4. ragg (local) f(...)
5. ragg:::get_dims(width, height, units, res)
Execution halted
```
Fixes the duplicate row.names error due to duplicate gene_names. Solved by concatenating `Ensembl_ID_gene_name`.
```
Quitting from …
```

Bugfixes pathway analysis
